[W 2024-03-19 14:02:11,949] Trial 0 failed with parameters: {'batch_size': 32, 'n_units': 8, 'learning_rate': 0.001, 'lr_decay': 0.85, 'lr_step': 2, 'negative_sampling': 6, 'loss': 'smooth_l1', 'update_freq': 32} because of the following error: NameError("name 'imvt2' is not defined").
Traceback (most recent call last):
  File "c:\Users\CYP\anaconda3\envs\torch\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_51060\3326290597.py", line 29, in objective
    auroc = train(batch_size,n_units,lr,lr_decay,lr_step,ns,loss,epochs,update_freq)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_51060\1020635424.py", line 2, in train
    network = imvt2(input_dim=params['state_dim'], output_dim=params['num_actions'], n_units=n_units, device=device).to(device)
NameError: name 'imvt2' is not defined. Did you mean: 'imvt'?
[W 2024-03-19 14:02:11,951] Trial 0 failed with value None.
[I 2024-03-19 14:02:49,629] A new study created in memory with name: no-name-0a11a618-6e04-46b7-b8f7-27e378221ef6