[W 2024-03-19 15:33:45,504] Trial 0 failed with parameters: {'batch_size': 32, 'n_units': 4, 'learning_rate': 1e-05, 'lr_decay': 0.85, 'lr_step': 10, 'negative_sampling': 4, 'loss': 'mse', 'update_freq': 16} because of the following error: NameError("name 'target' is not defined").
Traceback (most recent call last):
  File "c:\Users\CYP\anaconda3\envs\torch\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_64416\1960386959.py", line 29, in objective
    auroc = train(batch_size,n_units,lr,lr_decay,lr_step,ns,loss,epochs,update_freq)
  File "C:\Users\CYP\AppData\Local\Temp\ipykernel_64416\757422201.py", line 13, in train
    sampler = CustomSampler(train_data,batch_size,ns=ns,target=target)
NameError: name 'target' is not defined
[W 2024-03-19 15:33:45,505] Trial 0 failed with value None.
[I 2024-03-19 15:34:01,832] A new study created in memory with name: no-name-be918904-9e64-47cd-9d67-61bccbbdbe44